<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ClientesSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'nombre' => 'ARNI',
                'direccion' => 'Dirección de ARNI',
                'telefono' => '1234567890',
                'email' => 'arni@example.com',
                'tiene_credito' => true,
                'descuento' => 5.00,
                'limite_credito' => 1000.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'CAFETERÍA LA ESTRELLA',
                'direccion' => 'Dirección de Cafetería La Estrella',
                'telefono' => '9876543210',
                'email' => 'laestrella@example.com',
                'tiene_credito' => false,
                'descuento' => 0.00,
                'limite_credito' => 0.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'CASTROL',
                'direccion' => 'Dirección de CASTROL',
                'telefono' => '5555555555',
                'email' => 'castrol@example.com',
                'tiene_credito' => true,
                'descuento' => 10.00,
                'limite_credito' => 2000.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'CINE BUENA VISTA',
                'direccion' => 'Dirección de Cine Buena Vista',
                'telefono' => '5551234567',
                'email' => 'cinebuenavista@example.com',
                'tiene_credito' => false,
                'descuento' => 0.00,
                'limite_credito' => 0.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'DAYRON',
                'direccion' => 'Dirección de Dayron',
                'telefono' => '9998887777',
                'email' => 'dayron@example.com',
                'tiene_credito' => true,
                'descuento' => 8.00,
                'limite_credito' => 1500.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'EASIG',
                'direccion' => 'Dirección de EASIG',
                'telefono' => '3332221111',
                'email' => 'easig@example.com',
                'tiene_credito' => false,
                'descuento' => 0.00,
                'limite_credito' => 0.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'EL GUAJIRITO',
                'direccion' => 'Dirección de El Guajirito',
                'telefono' => '7776665555',
                'email' => 'elguajirito@example.com',
                'tiene_credito' => true,
                'descuento' => 6.00,
                'limite_credito' => 1200.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'EVOLUTION S.R.L',
                'direccion' => 'Dirección de Evolution S.R.L',
                'telefono' => '2223334444',
                'email' => 'evolution@example.com',
                'tiene_credito' => false,
                'descuento' => 0.00,
                'limite_credito' => 0.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'FERNANDO BAGÓ',
                'direccion' => 'Dirección de Fernando Bagó',
                'telefono' => '6665554444',
                'email' => 'fernandobago@example.com',
                'tiene_credito' => true,
                'descuento' => 7.00,
                'limite_credito' => 1800.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'JORGE HINOJOSA MADAN',
                'direccion' => 'Dirección de Jorge Hinojosa Madan',
                'telefono' => '1112223333',
                'email' => 'jorgehinojosa@example.com',
                'tiene_credito' => false,
                'descuento' => 0.00,
                'limite_credito' => 0.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'JORGE LUIS SUAREZ VALIENTE',
                'direccion' => 'Dirección de Jorge Luis Suarez Valiente',
                'telefono' => '9999999999',
                'email' => 'jorgeluissuarez@example.com',
                'tiene_credito' => true,
                'descuento' => 9.00,
                'limite_credito' => 1600.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'LA COCINITA',
                'direccion' => 'Dirección de La Cocinita',
                'telefono' => '4445556666',
                'email' => 'lacocinita@example.com',
                'tiene_credito' => false,
                'descuento' => 0.00,
                'limite_credito' => 0.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'LAS GUASIMAS',
                'direccion' => 'Dirección de Las Guasimas',
                'telefono' => '7777777777',
                'email' => 'lasguasimas@example.com',
                'tiene_credito' => true,
                'descuento' => 7.50,
                'limite_credito' => 1500.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'LEVIS',
                'direccion' => 'Dirección de Levis',
                'telefono' => '8889990000',
                'email' => 'levis@example.com',
                'tiene_credito' => false,
                'descuento' => 0.00,
                'limite_credito' => 0.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'LUIS ARMANDO ARIAS OLIVA',
                'direccion' => 'Dirección de Luis Armando Arias Oliva',
                'telefono' => '1111111111',
                'email' => 'luisarias@example.com',
                'tiene_credito' => true,
                'descuento' => 8.50,
                'limite_credito' => 1400.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'MARCOS',
                'direccion' => 'Dirección de Marcos',
                'telefono' => '2222222222',
                'email' => 'marcos@example.com',
                'tiene_credito' => false,
                'descuento' => 0.00,
                'limite_credito' => 0.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'MÁXIMO',
                'direccion' => 'Dirección de Máximo',
                'telefono' => '3333333333',
                'email' => 'maximo@example.com',
                'tiene_credito' => true,
                'descuento' => 7.00,
                'limite_credito' => 1700.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'MICHEL VEGA SANTANA',
                'direccion' => 'Dirección de Michel Vega Santana',
                'telefono' => '4444444444',
                'email' => 'michelvega@example.com',
                'tiene_credito' => false,
                'descuento' => 0.00,
                'limite_credito' => 0.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'MÓNACO',
                'direccion' => 'Dirección de Mónaco',
                'telefono' => '5555555555',
                'email' => 'monaco@example.com',
                'tiene_credito' => true,
                'descuento' => 6.50,
                'limite_credito' => 1300.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'OVIDIO PANTOJA ALVAREZ',
                'direccion' => 'Dirección de Ovidio Pantoja Alvarez',
                'telefono' => '6666666666',
                'email' => 'ovidio@example.com',
                'tiene_credito' => false,
                'descuento' => 0.00,
                'limite_credito' => 0.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'PEDRO ALBERTO',
                'direccion' => 'Dirección de Pedro Alberto',
                'telefono' => '7777777777',
                'email' => 'pedroalberto@example.com',
                'tiene_credito' => true,
                'descuento' => 8.00,
                'limite_credito' => 1600.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'PEDRO LUIS RODRIGUEZ ARCIA',
                'direccion' => 'Dirección de Pedro Luis Rodriguez Arcia',
                'telefono' => '8888888888',
                'email' => 'pedroluis@example.com',
                'tiene_credito' => false,
                'descuento' => 0.00,
                'limite_credito' => 0.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'PIZZERÍA BAHÍA',
                'direccion' => 'Dirección de Pizzería Bahía',
                'telefono' => '9999999999',
                'email' => 'pizzeriabahia@example.com',
                'tiene_credito' => true,
                'descuento' => 7.50,
                'limite_credito' => 1500.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'PROYECTO PM S.R.L.',
                'direccion' => 'Dirección de Proyecto PM S.R.L.',
                'telefono' => '1111111111',
                'email' => 'proyectopm@example.com',
                'tiene_credito' => false,
                'descuento' => 0.00,
                'limite_credito' => 0.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'ROBERTO MONTORO',
                'direccion' => 'Dirección de Roberto Montoro',
                'telefono' => '2222222222',
                'email' => 'robertomontoro@example.com',
                'tiene_credito' => true,
                'descuento' => 7.00,
                'limite_credito' => 1700.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'RUBEN',
                'direccion' => 'Dirección de Ruben',
                'telefono' => '3333333333',
                'email' => 'ruben@example.com',
                'tiene_credito' => false,
                'descuento' => 0.00,
                'limite_credito' => 0.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'TCP ALEXANDER',
                'direccion' => 'Dirección de TCP Alexander',
                'telefono' => '4444444444',
                'email' => 'tcpalexander@example.com',
                'tiene_credito' => true,
                'descuento' => 6.50,
                'limite_credito' => 1300.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'TCP CALIXTO',
                'direccion' => 'Dirección de TCP Calixto',
                'telefono' => '5555555555',
                'email' => 'tcpcalixto@example.com',
                'tiene_credito' => false,
                'descuento' => 0.00,
                'limite_credito' => 0.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'TCP JOSÉ LUIS',
                'direccion' => 'Dirección de TCP José Luis',
                'telefono' => '6666666666',
                'email' => 'tcpjoseluis@example.com',
                'tiene_credito' => true,
                'descuento' => 8.00,
                'limite_credito' => 1600.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'TCP LUISITO',
                'direccion' => 'Dirección de TCP LUISITO',
                'telefono' => '1234567890',
                'email' => 'luisito@example.com',
                'tiene_credito' => true,
                'descuento' => 5.00,
                'limite_credito' => 1000.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'TCP OMARITO',
                'direccion' => 'Dirección de TCP OMARITO',
                'telefono' => '9876543210',
                'email' => 'omarito@example.com',
                'tiene_credito' => false,
                'descuento' => 0.00,
                'limite_credito' => 0.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'TCP YANKIEL',
                'direccion' => 'Dirección de TCP YANKIEL',
                'telefono' => '5555555555',
                'email' => 'yankiel@example.com',
                'tiene_credito' => true,
                'descuento' => 10.00,
                'limite_credito' => 2000.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'YOANNI',
                'direccion' => 'Dirección de YOANNI',
                'telefono' => '1111111111',
                'email' => 'yoanni@example.com',
                'tiene_credito' => false,
                'descuento' => 0.00,
                'limite_credito' => 0.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'YURI',
                'direccion' => 'Dirección de YURI',
                'telefono' => '2222222222',
                'email' => 'yuri@example.com',
                'tiene_credito' => true,
                'descuento' => 5.00,
                'limite_credito' => 1500.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nombre' => 'OWNER',
                'direccion' => 'Dirección de OWNER',
                'telefono' => '2222222222',
                'email' => 'owner@example.com',
                'tiene_credito' => true,
                'descuento' => 5.00,
                'limite_credito' => 1500.00,
                'created_at' => date('Y-m-d H:i:s'),
            ],
        ];

        // Inserta los datos en la tabla 'clientes'
        $this->db->table('clientes')->insertBatch($data);

    }
}
